# Generated by Django 5.2.15 on 2026-07-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0014_crawledpage_has_mixed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('critical_issues', models.JSONField(default=list)),
                ('impact', models.TextField()),
                ('recommended_fix', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('quick_wins', models.JSONField(default=list)),
                ('client_friendly_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_recommendation', to='audits.audit')),
            ],
        ),
    ]
