# Generated by Django 5.2.15 on 2026-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='seo_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='client_friendly_explanation',
            field=models.TextField(default=''),
        ),
    ]
