# Generated by Django 5.2.15 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommendations', '0002_airecommendation_seo_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='recommended_fix',
            field=models.JSONField(default=list),
        ),
    ]
