# Generated by Django 6.0.6 on 2026-06-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pending'), ('RUNNING', '🔄 Running'), ('DONE', '✅ Done'), ('FAILED', '❌ Failed')], default='PENDING', max_length=20)),
                ('overall_Score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('h1', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('word_count', models.IntegerField()),
                ('load_time', models.FloatField()),
                ('on_page_score', models.IntegerField(null=True)),
                ('technical_score', models.IntegerField(null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.audit')),
            ],
        ),
    ]
