# Generated by Django 6.0.6 on 2026-06-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoissues',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoissues',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seoissues',
            name='issue_type',
            field=models.CharField(choices=[('ERROR', '❌ Error'), ('WARNING', '⚠️ Warning'), ('NOTICE', '📢 Notice')], default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoissues',
            name='url',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='audits.crawledpage'),
            preserve_default=False,
        ),
    ]
