# Generated by Django 6.0.6 on 2026-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_seoissues_description_seoissues_is_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='h2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='h3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='img_without_alt_tag',
            field=models.JSONField(null=True),
        ),
    ]
