# Generated by Django 6.0.6 on 2026-06-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_crawledpage_h2_crawledpage_h3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawledpage',
            old_name='img_without_alt_tag',
            new_name='img_without_alt_tags',
        ),
    ]
