# Generated by Django 6.0.6 on 2026-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_rename_img_without_alt_tag_crawledpage_img_without_alt_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
