# Generated by Django 6.0.6 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_audit_ai_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='bold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='canonical_tag_check',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
