# Generated by Django 6.0.6 on 2026-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_crawledpage_bold_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='key_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='keyword_density',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='keyword_in_h1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='keyword_in_h2_h3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='keyword_in_meta_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='keyword_in_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='url_structure_char_count',
            field=models.IntegerField(default=0),
        ),
    ]
