# Generated by Django 6.0.6 on 2026-06-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_audit_key_word_crawledpage_keyword_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='has_robots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audit',
            name='has_sitemap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='is_mobile_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='performance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoissues',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.audit'),
        ),
        migrations.AlterField(
            model_name='seoissues',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.crawledpage'),
        ),
    ]
