# Generated by Django 6.0.6 on 2026-06-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_audit_has_robots_audit_has_sitemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='is_crawlable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='is_hreflang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='is_schema_json',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='redirect_chainlength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='status_code404',
            field=models.BooleanField(default=False),
        ),
    ]
