# Generated by Django 6.0.6 on 2026-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_crawledpage_is_crawlable_crawledpage_is_hreflang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='broken_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='cumulative_layout_shift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='external_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='first_contentful_paint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='first_input_delay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='largest_contentful_paint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='time_to_first_byte',
            field=models.FloatField(default=0.0),
        ),
    ]
