# Generated by Django 6.0.6 on 2026-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_crawledpage_broken_links_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='core_web_vitals_performance_analysis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='mobile_font_readability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='mobile_tap_targets',
            field=models.BooleanField(default=False),
        ),
    ]
