# Generated by Django 6.0.6 on 2026-07-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_crawledpage_core_web_vitals_performance_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawledpage',
            old_name='core_web_vitals_performance_analysis',
            new_name='core_web_vitals_performance_score',
        ),
    ]
