# Generated by Django 6.0.6 on 2026-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_rename_core_web_vitals_performance_analysis_crawledpage_core_web_vitals_performance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='has_content_security_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_mobile_viewport_configuration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_strict_transport_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_valid_SSL',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='has_x_frame_options',
            field=models.BooleanField(default=False),
        ),
    ]
