# Generated by Django 6.0.6 on 2026-07-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0013_crawledpage_has_content_security_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='has_mixed_content',
            field=models.BooleanField(default=False),
        ),
    ]
