# Generated by Django 6.0.6 on 2026-07-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0014_crawledpage_has_mixed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('anchor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('rel', models.CharField(blank=True, max_length=255, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_broken', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('redirect', models.BooleanField(default=False)),
                ('redirect_target', models.URLField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='audits.crawledpage')),
            ],
        ),
    ]
