# Generated by Django 6.0.6 on 2026-07-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0015_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='redirect',
            new_name='redirects',
        ),
    ]
