# Generated by Django 6.0.6 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0016_rename_redirect_link_redirects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledpage',
            name='keyword_density',
            field=models.FloatField(default=0.0),
        ),
    ]
