# Generated by Django 6.0.6 on 2026-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0017_alter_crawledpage_keyword_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='redirect_target',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
