# Generated by Django 6.0.6 on 2026-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0018_alter_link_redirect_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='crawl_state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='hreflang_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
