# Generated by Django 6.0.6 on 2026-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0019_audit_crawl_state_crawledpage_hreflang_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='target_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
