from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import os
from django.conf import settings


def generate_pdf_report(report, branding=None):
    # PDF file path
    pdf_filename = f"report_{report.id}_{report.user.id}.pdf"
    pdf_path = os.path.join(settings.MEDIA_ROOT, 'reports', 'pdfs', pdf_filename)

    # Directory create karein
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=50, leftMargin=50,
        topMargin=50, bottomMargin=50
    )

    # Colors
    primary_color = colors.HexColor(branding.primary_color if branding else '#1a1a2e')
    company_name = branding.company_name if branding and branding.is_white_label else 'AI SEO Audit Platform'

    # Styles
    def style(name, size, bold=False, color='#333333', align=0, indent=0, before=0, after=4):
        return ParagraphStyle(name, fontSize=size,
            fontName='Helvetica-Bold' if bold else 'Helvetica',
            textColor=colors.HexColor(color),
            alignment=align, leftIndent=indent,
            spaceBefore=before, spaceAfter=after)

    title_s = style('ti', 22, bold=True, color='#1a1a2e', align=1, after=4)
    sub_s = style('su', 10, color='#666666', align=1, after=20)
    section_s = style('se', 13, bold=True, color='#1a1a2e', before=16, after=8)
    item_s = style('it', 10, color='#444444', indent=14, after=4)

    story = []

    # Header
    story.append(Paragraph(company_name, title_s))
    story.append(Paragraph("SEO AUDIT REPORT", style('st', 14, bold=True, color='#ffffff', align=1)))
    story.append(Paragraph(f"Website: {report.website_url} | Generated: {report.created_at.strftime('%d %B %Y')}", sub_s))
    story.append(HRFlowable(width="100%", thickness=2, color=primary_color))
    story.append(Spacer(1, 16))

    # Executive Summary
    story.append(Paragraph("EXECUTIVE SUMMARY", section_s))

    scores_data = [
        ['Overall SEO Score', f"{report.seo_score}/100"],
        ['Performance Score', f"{report.performance_score}/100"],
        ['Mobile Score', f"{report.mobile_score}/100"],
        ['Security Score', f"{report.security_score}/100"],
    ]

    scores_table = Table(scores_data, colWidths=[300, 150])
    scores_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#333333')),
        ('TEXTCOLOR', (1, 0), (1, -1), primary_color),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
    ]))
    story.append(scores_table)
    story.append(Spacer(1, 16))

    # Critical Issues
    story.append(Paragraph("CRITICAL ISSUES", section_s))
    story.append(Paragraph(f"- Total Issues Found: {report.total_issues}", item_s))
    story.append(Paragraph(f"- Critical Issues: {report.critical_issues}", item_s))
    story.append(Spacer(1, 16))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cccccc')))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"Generated by {company_name} | {report.website_url}",
        style('ft', 9, color='#999999', align=1)
    ))

    doc.build(story)
    return pdf_path, pdf_filename