# Generated by Django 5.2.15 on 2026-07-05 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(default='audit', max_length=50)),
                ('object_id', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('current_step', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('progress_percent', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('process_type', 'object_id')},
            },
        ),
    ]
